"use client";

import { motion } from "framer-motion";
import { CheckCircle2, AlertCircle, Brain, TrendingUp } from "lucide-react";
import Badge from "../ui/Badge";

export default function ScanResultPanel({ result }) {
  if (!result) return null;

  const isHealthy = result.prediction === "healthy" || result.label === "healthy";
  const confidence = result.confidence ? (result.confidence * 100).toFixed(1) : 0;

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
      className="bg-white rounded-[var(--radius-lg)] border border-[var(--border-default)] shadow-[var(--shadow-md)] overflow-hidden"
    >
      {/* Header */}
      <div className={`px-6 py-4 ${isHealthy ? "bg-[var(--color-success-light)]" : "bg-[var(--color-danger-light)]"}`}>
        <div className="flex items-center gap-3">
          <div className={`w-10 h-10 rounded-full flex items-center justify-center ${isHealthy ? "bg-[var(--color-success)]/10" : "bg-[var(--color-danger)]/10"}`}>
            {isHealthy ? <CheckCircle2 className="w-5 h-5 text-[var(--color-success)]" /> : <AlertCircle className="w-5 h-5 text-[var(--color-danger)]" />}
          </div>
          <div>
            <h3 className="text-base font-semibold text-[var(--text-primary)]">
              {isHealthy ? "Healthy Pattern Detected" : "Parkinson's Indicators Found"}
            </h3>
            <p className="text-xs text-[var(--text-muted)] mt-0.5">AI analysis complete</p>
          </div>
        </div>
      </div>

      {/* Metrics */}
      <div className="px-6 py-5 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-sm text-[var(--text-secondary)]">
            <Brain className="w-4 h-4" />
            Classification
          </div>
          <Badge variant={isHealthy ? "success" : "danger"}>
            {isHealthy ? "Healthy" : "Parkinson's"}
          </Badge>
        </div>
        <div>
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2 text-sm text-[var(--text-secondary)]">
              <TrendingUp className="w-4 h-4" />
              Confidence
            </div>
            <span className="text-sm font-bold text-[var(--text-primary)]">{confidence}%</span>
          </div>
          <div className="h-2.5 bg-[var(--color-neutral-100)] rounded-full overflow-hidden">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${confidence}%` }}
              transition={{ duration: 1, delay: 0.3, ease: [0.4, 0, 0.2, 1] }}
              className={`h-full rounded-full ${isHealthy ? "bg-[var(--color-success)]" : "bg-[var(--color-danger)]"}`}
            />
          </div>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="px-6 py-3 bg-[var(--color-neutral-50)] border-t border-[var(--border-default)]">
        <p className="text-[11px] text-[var(--text-muted)]">
          This result is generated by an AI model (EfficientNet) and should be used as a screening aid only. Always consult a qualified neurologist for clinical diagnosis.
        </p>
      </div>
    </motion.div>
  );
}
